(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(diredp-hide-details-initially-flag nil)
 '(fringe-mode '(12 . 12) nil (fringe))
 '(global-dired-hide-details-mode t)
 '(org-agenda-files '("~/org/todo/daily.org"))
 '(org-modern-todo-faces '(("DO" :background "yellow" :foreground "black")))
 '(org-support-shift-select t)
 '(package-selected-packages
   '(treemacs-all-the-icons smartparens treemacs-icons-dired treemacs treeview pretty-hydra hydra company olivetti imenu-list org-modern flymake-jshint typescript-mode org-roam edit-indirect flymake-php flymake-phpcs package-lint-flymake diff-hl git-gutter-fringe+ solaire-mode rainbow-delimiters telephone-line helm-mode-manager use-package sml-modeline smart-mode-line lua-mode golden-ratio doom-themes all-the-icons))
 '(sml/show-frame-identification t)
 '(treemacs-icons-dired-mode t nil (treemacs-icons-dired))
 '(warning-suppress-log-types
   '(((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))))
 '(warning-suppress-types
   '(((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))
     ((unlock-file))))
 '(window-divider-default-bottom-width 2)
 '(window-divider-default-right-width 3))
(put 'dired-find-alternate-file 'disabled nil)
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#191919" :foreground "honeydew" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight light :height 113 :width normal :foundry "UKWN" :family "Iosevka Fixed SS05"))))
 '(auto-dim-other-buffers-face ((t (:background "#161616"))))
 '(custom-comment ((t (:background "#282828" :foreground "#d4d4d4" :slant italic :family "Victor Mono"))))
 '(fill-column-indicator ((t (:stipple nil :foreground "gray5" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))))
 '(font-lock-builtin-face ((t (:foreground "spring green"))))
 '(font-lock-comment-face ((t (:foreground "hot pink" :slant italic :width extra-condensed :family "Victor Mono"))))
 '(font-lock-constant-face ((t (:foreground "salmon"))))
 '(font-lock-function-name-face ((t (:foreground "turquoise" :weight ultra-bold))))
 '(font-lock-keyword-face ((t (:foreground "light slate blue" :weight bold))))
 '(font-lock-string-face ((t (:background "#121212" :foreground "LightGoldenrod1" :slant italic :width ultra-condensed :family "Victor Mono"))))
 '(font-lock-variable-name-face ((t (:foreground "green yellow"))))
 '(fringe ((t (:foreground "hot pink"))))
 '(helm-buffer-not-saved ((t (:foreground "color-118"))))
 '(helm-buffer-saved-out ((t (:background "black" :foreground "color-118"))))
 '(hl-line ((t (:background "#333333"))))
 '(italic ((t (:slant italic :family "Victor Mono"))))
 '(line-number ((t (:inherit default :background "#0a0a0a" :foreground "#333333" :strike-through nil :underline nil :slant normal :weight bold :height 0.8))))
 '(line-number-current-line ((t (:inherit default :background "aquamarine" :foreground "medium slate blue" :strike-through nil :underline nil :slant normal :weight bold :height 0.8))))
 '(markdown-header-face ((t (:inherit bold :foreground "green yellow" :height 1.1))))
 '(minibuffer-prompt ((t (:background "#161616" :foreground "LightGoldenrod1" :inverse-video nil))))
 '(mode-line ((t (:background "medium slate blue" :foreground "pink" :box nil :height 1.0))))
 '(mode-line-inactive ((t (:background "#0a0a0a" :foreground "gray60" :inverse-video nil :box nil :height 1.0))))
 '(org-modern-internal-link ((t (:inherit (org-modern-done default) :background "hot pink"))))
 '(org-tag ((t (:foreground "salmon" :inverse-video t :weight normal))))
 '(sml/col-number ((t (:inherit sml/global :height 1.0))))
 '(sml/filename ((t (:inherit sml/global :foreground "pink" :weight bold))))
 '(sml/git ((t (:foreground "goldenrod1"))))
 '(sml/global ((t (:foreground "DarkSlateGray4" :inverse-video nil))))
 '(sml/line-number ((t (:inherit sml/modes :weight extra-bold :height 0.8))))
 '(sml/prefix ((t (:inherit sml/global :foreground "#777777"))))
 '(sml/time ((t (:inherit nil :distant-foreground "black" :foreground "#999999" :weight extra-bold :height 0.9 :width ultra-condensed :family "Iosevka Fixed SS05"))))
 '(sml/vc ((t (:inherit sml/git :distant-foreground "#d4d4d4" :inverse-video nil :overline t :weight bold :height 1.0))))
 '(solaire-default-face ((t (:inherit default :background "#0a0a0a"))))
 '(telephone-line-accent-active ((t (:background "aquamarine" :foreground "medium slate blue" :weight bold :width ultra-condensed :family "Iosevka"))))
 '(telephone-line-accent-inactive ((t (:background "#0a0a0a" :foreground "#d4d4d4"))))
 '(vertical-border ((t (:background "#121212" :foreground "medium slate blue"))))
 '(web-mode-keyword-face ((t (:foreground "medium slate blue"))))
 '(web-mode-string-face ((t (:inherit font-lock-string-face :foreground "#FBE3BF"))))
 '(window-divider ((t (:inherit vertical-border :background "white" :foreground "#0a0a0a")))))
